dir.upload.remote = /images/sampleapp/
dir.upload.remote.original = /images/sampleapp/original/
dir.upload.remote.file = /non-images/sampleapp/
dir.upload.local = /opt/upload/
dir.upload.local.original = /opt/upload/original/
file.token=***
lotte.key=***
