FROM sample.registry.com/base/java.app.env17:latest

USER app
RUN mkdir /apps/sample
ADD ./api.jar /apps/sample/

# Java 환경 설정
ENV JAVA_HOME /apps/jdk/17.0.2
ENV PATH $PATH:$JAVA_HOME/bin

# scouter 환경 설정
ENV SCOUTER_DIR /apps/scouter/2.15.0
ENV SCOUTER_NAME sampleapp-api
ENV JAVA_AGENT /apps/scouter/2.15.0/agent.java/scouter.agent.jar
ENV SCOUTER_CONF /apps/scouter/2.15.0/agent.java/conf/scouter.conf

USER root

RUN yum install -y fontconfig libfreetype6

# 스카우터 설정
RUN echo 'net_collector_ip=localhost' >> /apps/scouter/2.15.0/agent.host/conf/scouter.conf
RUN echo 'net_collector_udp_port=6100' >> /apps/scouter/2.15.0/agent.host/conf/scouter.conf
RUN echo 'net_collector_tcp_port=6100' >> /apps/scouter/2.15.0/agent.host/conf/scouter.conf

RUN echo 'net_collector_ip=localhost' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'net_collector_udp_port=6100' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'net_collector_tcp_port=6100' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf

RUN echo 'trace_http_client_ip_header_key=X-Forwarded-For' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'profile_http_parameter_enabled=true' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'profile_http_header_enabled=true' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'xlog_lower_bound_time_ms=10' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf
RUN echo 'counter_interaction_enabled=true' >> /apps/scouter/2.15.0/agent.java/conf/scouter.conf

CMD ["sh", "-c", "source /etc/profile && cd /apps/scouter/2.15.0/agent.host && ./host.sh && java -javaagent:$JAVA_AGENT -Dscouter.config=$SCOUTER_CONF -Dobj_name=$SCOUTER_NAME -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED -Djdk.attach.allowAttachSelf=true -jar -Dserver.port=7101 /apps/sample/api.jar"]
