FROM sample.registry.com/base/java.app.env17:latest

USER app
RUN mkdir /apps/sample
ADD ./webapi.jar /apps/sample/

# Java 환경 설정
ENV JAVA_HOME /apps/jdk/17.0.2
ENV PATH $PATH:$JAVA_HOME/bin

USER root

CMD ["sh", "-c", "source /etc/profile &&  java -Dfile.encoding=UTF-8 -Xms1024m -Xmx3072m -jar -Dserver.port=7103 /apps/sample/webapi.jar"]
